CREATE TABLE clients (
    id           BIGINT PRIMARY KEY,
    user_id      BIGINT,
    group_id     BIGINT,
    date         TIMESTAMP,
    name         TEXT,
    middlename   TEXT,
    surname      TEXT,
    extradata    TEXT,
    birthday     DATE,
    birthday_place TEXT,
    phone        TEXT,
    email        TEXT,
    social       TEXT,
    address      TEXT,
    doc_title    TEXT,
    doc_series   TEXT,
    doc_code     TEXT,
    doc_when     DATE,
    doc_valid    DATE,
    doc_where    TEXT,
    comment      TEXT,
    anketa       TEXT,
    bl           BOOLEAN,
    vip          BOOLEAN,
    adv          BOOLEAN,
    gender       SMALLINT,
    foreigner    BOOLEAN,
    is_live      BOOLEAN,
    pref         SMALLINT
);